### ISSUE TITLE
Wrong script for 324372.ogg

### ISSUE THREAD

**Issue by ujl123** [zource-dev/bigwigs-real-voice#1]
In the file 324372.ogg, the speech says "Reaping Winds equals Winds". I'm fairly certain this  is an error.

**Comment by 3axap4eHko** [comment]
Hey @ujl123 here is the wowhead spellId https://www.wowhead.com/spell=324372/reaping-winds

**Comment by ujl123** [comment]
> Hey @ujl123 here is the wowhead spellId https://www.wowhead.com/spell=324372/reaping-winds

Sorry I meant to say that the audio file says "Reaping Winds equal winds". My question is, why does it say "equal winds" as well? I can't attach .ogg files to this ticket, but it sounds like it's saying "reaper winds equal winds".

**Comment by ujl123** [comment]
[324372.zip](https://github.com/user-attachments/files/17091451/324372.zip)

Zipped audio file for context

**Comment by 3axap4eHko** [comment]
got it, will fix in the new version
